### ISSUE TITLE
Add support for 1.19.3

### ISSUE THREAD

**Issue by mrjasonn** [kvverti/colormatic#128]
It's crashing on 1.19.3 so need to update it to be compatible + realms now use 1.19.3 so need to update this mod.
@kvverti 
#126 They made a usable version for 1.19.3 so can just merge pull request with (possibly) few changes.

**Comment by TechPro424** [comment]
Yes please update

**Comment by velnias75** [comment]
Made it at least compiling on `1.19.3`, but currently the mixins are not ported.
So it is not really tested yet, but with all - not yet working mixins - excluded the result looked already good.

@kvverti: You may use this as starting point? It already includes my path for #6 
Here is my tag: https://github.com/velnias75/colormatic/tree/JustCompileOn-1.19.3 (on branch *1.19.3*)

**Comment by velnias75** [comment]
I got it to work so far, that at least *Minecraft* is playable in `1.19.3`
Either @kvverti will fix the rest, or somebody will help me or take over my branch.

Current sources can be found here:  https://github.com/velnias75/colormatic/tree/1.19.3

This is a *zipped jar* (since GitHub doesn't accept *jars* as attachments): [colormatic-3.1.3-snapshot+mc.1.19.3.zip](https://github.com/kvverti/colormatic/files/10705306/colormatic-3.1.3-snapshot%2Bmc.1.19.3.zip)

**Comment by mstreurman** [comment]
[crash-2023-02-13_01.44.07-client.txt](https://github.com/kvverti/colormatic/files/10717762/crash-2023-02-13_01.44.07-client.txt)

Minecraft doesn't start with this new version of colormatic. Attached the crashlog

**Comment by velnias75** [comment]
As I told, I need either help, ot @kvverti will may use it as starting point.
I just tried to get it at least running on my PC.

**Comment by mstreurman** [comment]
> As I told, I need either help, ot @kvverti will may use it as starting point. I just tried to get it at least running on my PC.

This was in no way an attack on you or saying you need to fix it, I just wanted to give feedback and a crashlog so there is more information available to work with.

**Comment by RU-B0** [comment]
Just wanted to help out:
2 crashes, quilt (probs ignore) and fabric. They have the same error, compiled on my pc, here u go. No idea if this is useful but yk.
[FABRIC.txt](https://github.com/kvverti/colormatic/files/11194547/FABRIC.txt)
[QUILT.txt](https://github.com/kvverti/colormatic/files/11194548/QUILT.txt)
I got a window on each, white screen, then it instantly crashed with "The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1092 failed"
I wish this mod was simpler so that it was easy to update...but i like the features...
have a good day!

**Comment by kvverti** [comment]
Consolidating 1.20 update in #136
